### ISSUE TITLE
Memory viewer isn't displaying anything

### ISSUE THREAD

**Issue by deananorth** [mortbopet/Ripes#102]
Operating system: Windows 10 21H1
Version: Continuous

Expected result: Memory display should show values in memory.
Actual result: Memory display is blank. Combo boxes at the bottom of the screen do not seem to work. No error messages appear as to why memory.

Ripes Continuous
![image](https://user-images.githubusercontent.com/59711369/125559387-a92570d3-3270-4f4a-a814-afa305a1fb43.png)

Ripes 2.2.1
![image](https://user-images.githubusercontent.com/59711369/125559859-d17e530e-bc18-43af-942c-1bcdc5e13198.png)

**Comment by mortbopet** [comment]
Hi @deananorth, this should hopefully have been fixed in 5d8ee3c7dc9b20968f51557e95ea4c1146d02b44 - please verify in the latest continuous release - thank you! :+1:

**Comment by deananorth** [comment]
![image](https://user-images.githubusercontent.com/59711369/125664824-cc5d1080-49d8-4580-888d-fbdcd32c6726.png)

Tried the latest continuous released (Commit ce8d568, released 10 hours ago as of this post)
it seems to have worked.

Thanks for your help.
