### ISSUE TITLE
[RVC][Tracker] Support for RISC-V "C" extension

### ISSUE THREAD

**Issue by mortbopet** [mortbopet/Ripes#125]
This is a tracking issue for tracking the implementation of the RISC-V compressed ISA extension in Ripes.

- [x] #124
- [x] #126
- [x] #127
- [x] #128
- [x] #129
- [x] #130
- [x] #132
- [x] #137
- [x] #144 
- [x] #152 
- [x] #156
- [x] #157
- [x] #166

Discussion on support for the C extension: https://github.com/mortbopet/Ripes/discussions/119.

**Comment by Zikon328** [comment]
Disassembler does not correct dissasemble register, when reduce range register x8-x15
and not error for  reduce reg in asm source.
( Asm and C  mode )
![Image](https://github.com/user-attachments/assets/e1e8e1dd-f0a3-409d-9a13-9268ff9a0dfa)

Command  c.beqz  and  c.bnez   not  valid  compute  offset.
( Asm mode )

format command   c.lw and  c.sw
c.lw  rd,  rs,  offset

not really   
c.lw   rd,  offset(rs)

**Comment by Xiamatsu** [comment]
Branch and jump commands "C" instructions is not valid offset !
c.beqz c.bnez
c.j c.jal
The absolute address is used, not relative.

Commands c.lw and c.sw - used only format
c.lw rd, rs, offset

can do [ c.lw rd, (offset)rs ] ?
