### ISSUE TITLE
[RVC] Add support for compiling with the compressed extension

### ISSUE THREAD

**Issue by mortbopet** [mortbopet/Ripes#126]
When the "C" extension is enabled, this should also be forwarded to the compiler when compiling C programs.

Things we need to validate are:
- Are we adding the "c" extension in the right way for `--march`?
- Are we able to disassemble compiled binaries with compressed instructions?

**Comment by lcgamboa** [comment]
> When the "C" extension is enabled, this should also be forwarded to the compiler when compiling C programs.
> 
> Things we need to validate are:
> 
>     * Are we adding the "c" extension in the right way for `--march`?
Yes, but multilib don´t have precompiled rv32imc libs (only rv32imac) and use rv32im instead. Only user program will use C instructions.

>     * Are we able to disassemble compiled binaries with compressed instructions?
Yes
