### ISSUE TITLE
Console view in editor mode

### ISSUE THREAD

**Issue by schoeberl** [mortbopet/Ripes#131]
Single stepping a program in editor mode is a nice view for using Ripes as an ISA simulator (without looking into pipeline details). It would be nice if this view can also show the console output.

**Comment by mortbopet** [comment]
Added a setting for this in #1fffcb4 - you can test it out in the [latest continuous build](https://github.com/mortbopet/Ripes/releases/tag/continuous). By now, it's off by default - let me know if this is something which you'd expect to be enabled by default.

**Comment by schoeberl** [comment]
I would like to see Ripes also as a plain ISA simulator (to drop Venus), which it is when selecting the single-cycle processor and stay in the editor view. Maybe this should then be on by default.

**Comment by mortbopet** [comment]
Agreed. 3c98bb0 enables the console by default.
