### ISSUE TITLE
ninja: error: unknown target 'install'

### ISSUE THREAD

**Issue by Petross404** [mortbopet/Ripes#141]
I am trying to write an ebuild for Ripes but Portage can't install it after compilation. I think cmake doesn't generate an install target:

```
OUTPUT(Ripes elf64-x86-64)
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: total time in link: 0.893296
>>> Source compiled.
>>> Test phase [not enabled]: app-emulation/ripes-9999

>>> Install app-emulation/ripes-9999 into /tmp/portage/app-emulation/ripes-9999/image
 * Source directory (CMAKE_USE_DIR): "/tmp/portage/app-emulation/ripes-9999/work/ripes-9999"
 * Build directory  (BUILD_DIR):     "/tmp/portage/app-emulation/ripes-9999/work/ripes-9999_build"
ninja: error: unknown target 'install'
 * ERROR: app-emulation/ripes-9999::guru failed (install phase):
 *   died running ninja install
 * 
 * Call stack:
 *     ebuild.sh, line  127:  Called src_install
 *   environment, line 2665:  Called cmake_src_install
 *   environment, line 1252:  Called die
 * The specific snippet of code:
 *       DESTDIR="${D}" ${CMAKE_MAKEFILE_GENERATOR} install "$@" || die "died running ${CMAKE_MAKEFILE_GENERATOR} install";
 * 
```
I can create a PR for this.

**Comment by Petross404** [comment]
Since GH can go have sex with itself and it's "personal access token" stupidity, I can't push to my own fork. Please let me share the patch at least.

```patch
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 6c33e35..bd7fb0f 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -9,7 +9,11 @@ if(CCACHE_PROGRAM)
     set_property(GLOBAL PROPERTY RULE_LAUNCH_COMPILE "${CCACHE_PROGRAM}")
 endif()
 
-project(Ripes CXX)
+project(Ripes
+        LANGUAGES CXX
+        DESCRIPTION "A graphical processor simulator and assembly editor for the RISC-V ISA"
+        HOMEPAGE_URL "https://github.com/mortbopet/Ripes")
+include(GNUInstallDirs) #Must exist after declaring a project
 
 # Error flags on everything but MSVC
 if(NOT MSVC)
@@ -103,3 +107,16 @@ add_executable(${APP_NAME} ${SYSTEM_FLAGS} ${ICONS_SRC} ${EXAMPLES_SRC} ${LAYOUT
 target_link_libraries(${APP_NAME} Qt5::Core Qt5::Widgets)
 # Link Ripes library
 target_link_libraries(${APP_NAME} ripes_lib)
+
+install(TARGETS ${APP_NAME}
+    RUNTIME DESTINATION ${CMAKE_INSTALL_FULL_BINDIR}
+)
+
+install(TARGETS ripes_lib
+    fancytabbar_lib
+    ${VSRTL_CORE_LIB}
+    ${VSRTL_GRAPHICS_LIB}
+    ${VSRTL_COMPONENTS_LIB}
+    ${VSRTL_INTERFACE_LIB}
+    LIBRARY DESTINATION ${CMAKE_INSTALL_FULL_LIBDIR}
+)
```
Stupid GH.

**Comment by Petross404** [comment]
Also, for some reason portage compiles libraries to dynamic while  when I am just manually compiling I am getting static libraries. Can we provide an option to fixate this in a deterministic way?

**Comment by mortbopet** [comment]
> I can't push to my own fork

I had a bit of issues with this as well; assuming you have SSH keys set up with you github account, it should suffice to (re)set the origin to the SSH remote (git@github.com:mortbopet/Ripes.git) instead of the HTTPS remote (https://github.com/mortbopet/Ripes.git).

**Comment by Petross404** [comment]
> #143 reworked the library generation a bit, which also marked the (Ripes) libraries explicitly as static libraries. There might still be issues with the VSRTL libraries... let me know if the commit fixed the issue!

This is what I am getting:
```
>>> Install app-emulation/ripes-9999 into /tmp/portage/app-emulation/ripes-9999/image
 * Source directory (CMAKE_USE_DIR): "/tmp/portage/app-emulation/ripes-9999/work/ripes-9999"
 * Build directory  (BUILD_DIR):     "/tmp/portage/app-emulation/ripes-9999/work/ripes-9999_build"
[1/2] Install the project...
-- Install configuration: "RelWithDebInfo"
-- Installing: /tmp/portage/app-emulation/ripes-9999/image/usr/bin/Ripes
-- Set runtime path of "/tmp/portage/app-emulation/ripes-9999/image/usr/bin/Ripes" to ""
-- Installing: /tmp/portage/app-emulation/ripes-9999/image/usr/lib64/libripes_lib.a
-- Installing: /tmp/portage/app-emulation/ripes-9999/image/usr/lib64/libvsrtl_core_lib.so
-- Installing: /tmp/portage/app-emulation/ripes-9999/image/usr/lib64/libvsrtl_gfx_lib.so
-- Set runtime path of "/tmp/portage/app-emulation/ripes-9999/image/usr/lib64/libvsrtl_gfx_lib.so" to ""
-- Installing: /tmp/portage/app-emulation/ripes-9999/image/usr/lib64/libvsrtl_cmp_lib.so
-- Installing: /tmp/portage/app-emulation/ripes-9999/image/usr/lib64/libvsrtl_int_lib.so
>>> Completed installing app-emulation/ripes-9999 into /tmp/portage/app-emulation/ripes-9999/image

 * Final size of build directory: 293668 KiB (286.7 MiB)
 * Final size of installed tree:   65388 KiB ( 63.8 MiB)

strip: x86_64-pc-linux-gnu-strip --strip-unneeded -N __gentoo_check_ldflags__ -R .comment -R .GCC.command.line -R .note.gnu.gold-version
   /usr/lib64/libripes_lib.a
   /usr/lib64/libvsrtl_core_lib.so
   /usr/lib64/libvsrtl_cmp_lib.so
   /usr/lib64/libvsrtl_gfx_lib.so
   /usr/lib64/libvsrtl_int_lib.so
   /usr/bin/Ripes
```

Now, I see some issues that I need to figure out.
1) CMake configurates the build type as "RelWithDebInfo" while in portage this should be "Gentoo" (`-DCMAKE_BUILD_TYPE=Gentoo`).
2) Are all these libraries external projects that are fetched recursively? If yes, I must create ebuilds for them separately so they can be system-installed dependencies (that's the preferred way for Gentoo). Most importantly, the dynamic libraries must have a version* but that's easily doable when declaring the library.

*
```
/usr/lib64/libQt5Core.so
/usr/lib64/libQt5Core.so.5
/usr/lib64/libQt5Core.so.5.15
/usr/lib64/libQt5Core.so.5.15.2
```

3) I don't know what is the case with static libraries and their versioning scheme. They are supposed to be "merged" in the final binary but I don't know anything more about them or how they are installed.

**Comment by mortbopet** [comment]
It looks like those libraries indeed are the VSRTL libraries - let me go ahead and modify that project to make sure that the VSRTL core/cmp/gfx/int libraries are static.

> Are all these libraries external projects that are fetched recursively? 

Those libraries should be available in the Qt install on the build machine. The current CD uses [linuxdeployqt](https://github.com/probonopd/linuxdeployqt) to create an AppImage bundle... maybe some of the magic there can be weaved into getting the portage build up and running.
