### ISSUE TITLE
Can not get Executable code from Assembly

### ISSUE THREAD

**Issue by DataSailor** [mortbopet/Ripes#150]
Today, I suddenly found that I couldn't get the corresponding executable code after completing the assembly code. This problem occurs in newer versions (such as v2.2.3-35 and v2.2.3), but not in older versions (such as v2.1.0).
Until yesterday, Ripes was able to display the code normally.

![image](https://user-images.githubusercontent.com/39119487/138060615-4dd55808-e9f5-4ac0-9f3c-0bcb190e4056.png)
![image](https://user-images.githubusercontent.com/39119487/138060674-cd4dd2b0-20f8-416b-bf78-5db3ff0a6ebc.png)

I’m running win10 19043.1288.
I just started to learn assembly and use Rips a few days ago. Maybe it's just my operation error.

**Comment by jnoche** [comment]
This error has happened to me at least twice while using version 2.2.3.  In both cases, I don't remember changing the .text section start address.

**Comment by jnoche** [comment]
I had just had the error occur to me now, so I went to "Settings>Compiler" and changed the .text section start address from 0xFFFFFFFD to 0x00000000.  So with the error fixed, I started using the program again.  I entered the comment above and while I was typing it, I went back to "Settings>Compiler" and I see that the .text section start address has changed again to 0xFFFFFFFD.  That is, it changed by itself!

**Comment by mortbopet** [comment]
Hi @jnoche ; does this also happen for the continuous release? One issue that was solved in relation to what is reported here was that settings values which represented unsigned values were being reload incorrectly (14987afb111ffc0c193afca42f2cb8b835bde2a3).

**Comment by jnoche** [comment]
Thanks for the reply.  I haven't tried it with the continuous release.  I'll try it next time.
