### ISSUE TITLE
[RVC] Resetting RV-C single cycle processor is very slow

### ISSUE THREAD

**Issue by mortbopet** [mortbopet/Ripes#156]
To reproduce:
- Load the consoleInput.c example and build it
- Toggle run
- Untoggle run
- press reset

While not crashing, Ripes takes _very_ long to complete the reset.

**Comment by lcgamboa** [comment]
I did several tests and this problem really happens. There was no crash with me, but the problem appears randomly. Happens with extension C enabled or disabled. 
Initially I think it might be something related to the new address caching implementation, so I'll keep looking. I will try to use linux perf to find the problem, as the problem increases CPU utilization.
