### ISSUE TITLE
[RVC] Incorrect behaviour when executing `consoleInput.c` on single cycle RVC

### ISSUE THREAD

**Issue by mortbopet** [mortbopet/Ripes#157]
To reproduce:

- Load the consoleInput.c example and build it
- Press run
- Enter in i.e. "10"; an invalid number error will be reported back. Enter 10 again; this time it is accepted.
- Enter in i.e."2" and do as above
- The correct value is calculated

Something slight must be going wrong here - we're managing to pass the values from user input into the stdio buffers; however, the "invalid number..." errors should obviously not occur. This only happens when we enable the "C" extension when selecting the processor.

**Comment by lcgamboa** [comment]
I have tried these steps several times and I have not been able to reproduce this error. I'm using Debian Linux for development.
