### ISSUE TITLE
Add support for autoformatting source code in Assembly or C 

### ISSUE THREAD

**Issue by lcgamboa** [mortbopet/Ripes#181]
> An automatic code formatting option would also be helpful. 

Source code auto formatting is a common tool in most editors. Although not simple to implement it would be a nice addition for Ripes users. 

_Originally posted by @mortbopet in https://github.com/mortbopet/Ripes/issues/162#issuecomment-978976066_

**Comment by mortbopet** [comment]
Currently looking in to this. My plan is to hook into using a formatter program (like `clang-format`) and run it on file save.
