### ISSUE TITLE
Dropping 0x0d bytes when reading a binary file

### ISSUE THREAD

**Issue by schoeberl** [mortbopet/Ripes#186]
Hi Morten, when reading binary files bytes containing CR (0x0d) are dropped. I think I know where this problem comes from. Windows text files end with CR and LF, Unix with LF only. The C library functions expect line endings with LF only. Therefore, when you open a file in text mode in Windows it drops all CR (ASCII code 0c0d). Open a binary file in Windows in binary mode, use the O_BINARY option on open.

**Comment by mortbopet** [comment]
Thank you for catching that; should be fixed in #186, let me know if it works for you :+1: .
