### ISSUE TITLE
Simple assembler optimization

### ISSUE THREAD

**Issue by Shadlock0133** [mortbopet/Ripes#19]
Currently for `li a0, 0xff000000` assembler will generate two instructions `lui x10 1044480; addi x10 x10 0`. The second instruction is practically a nop.

A simple check in assembling immediate instructions with the same register and value of zero (for addi, ori, xori, slli, srli, srai) should be enough for starters.

**Comment by mortbopet** [comment]
Thank you for mentioning it! The optimization is implemented in the referenced commit
