### ISSUE TITLE
Not saving file if directory does not exist

### ISSUE THREAD

**Issue by NANDLAB** [mortbopet/Ripes#190]
Hello,
if I try to save an assembly source file as `/home/user/Ripes/test.s`, but the directory `/home/user/Ripes` does not exist, the file is not saved and no error is shown to the user. Instead, Ripes shows the message `Saved files /home/user/Ripes/test.s` at the bottom, which is misleading.
Can you please either show an error message or create the Ripes directory automatically?

**Comment by mortbopet** [comment]
Sorry for the delay; should be fixed in 37ceb9f, let me know if it works for you.

**Comment by NANDLAB** [comment]
It works! Now it creates the directory, if it does not exist. Thank you!
