### ISSUE TITLE
local labels not working ?

### ISSUE THREAD

**Issue by hl037** [mortbopet/Ripes#199]
Hi,
From here : https://github.com/riscv-non-isa/riscv-asm-manual/blob/master/riscv-asm.md#labels I is said we can use numeric local labels...

...But I get an error when trying to do so... Is it expected ?

![image](https://user-images.githubusercontent.com/2771764/158289500-b6891843-6d31-4ca9-be41-066cf70a594f.png)

**Comment by mortbopet** [comment]
Hi @hl037 

That part of the assembly spec has not been implemented in the Ripes assembler. It shouldn't be too hard to implement though; I'll take a look at it. Thank you for raising the issue!

**Comment by mortbopet** [comment]
@hl037 took a stab at writing an implementation for this - the feature should be available in the [continuous release](https://github.com/mortbopet/Ripes/releases/tag/continuous). Please let me know if it works for you.
