### ISSUE TITLE
Same logic but different result using bge

### ISSUE THREAD

**Issue by gustavoisidio** [mortbopet/Ripes#2]
<img width="638" alt="screen shot 2018-08-29 at 00 29 11" src="https://user-images.githubusercontent.com/9287750/44763745-f73ce100-ab22-11e8-8614-eeb9af79cd40.png">

Here, line 12 on the right is equivalent to lines 12 and 13 on the left. However, we have different results for t1 and t2. If I'm wrong please let me know.

**Comment by mortbopet** [comment]
Fixed in 396349095b0660582097f6aac42bd5eb81133fbc 
Thank you very much for reporting the issue.
