### ISSUE TITLE
Pipeline stage visualization

### ISSUE THREAD

**Issue by ashriram** [mortbopet/Ripes#209]
On MacOS Monterey 12.3
Ripes: v 2.2.4

The pipeline stage diagram does not seem to update
![image](https://user-images.githubusercontent.com/4432524/172220957-f0259189-4846-49cb-a6e7-62f6dd098579.png)

**Comment by mortbopet** [comment]
Thank you for reporting the issue; unfortunately, i don't own a MacOS device, so fixing this issue right away will be a bit tricky - help is much appreciated!

**Comment by mortbopet** [comment]
I see this is an issue on my local machine as well (win11), so I should be able to take a closer look at it.

**Comment by ashriram** [comment]
Mac OS 12.3
Confirming fixed . Closing the issue.
