### ISSUE TITLE
Non-stop opening

### ISSUE THREAD

**Issue by chuanEgg** [mortbopet/Ripes#212]
My OS is ubuntu 20.04.
I installed the AppImage file and used `chmod a+x Ripes-v2.2.4-linux-x86_64.AppImage` and `./Ripes-v2.2.4-linux-x86_64.AppImage` to run the app. However, it lagged for a while, and suddenly multiple Ripes opened up and didn't stop until a reboot my system. In addition, many `AppRun` can be sighted in the System Monitor. I think I need help, and I apologize for my poor English.
![Screenshot from 2022-07-05 22-53-04](https://user-images.githubusercontent.com/94686998/177361395-9f13ce5e-84f8-44ba-b480-20aa45739fc5.png)
here's a screenshot of the chaos.

**Comment by mortbopet** [comment]
Hmm, very strange! i run ubunt 20.04 myself and have never had this happen. What happens if you try to unpack the appimage and run the binary directly?
```sh
./Ripes-v2.2.4-linux-x86_64.AppImage --appimage-extract
mv squashfs-root/usr/bin/Ripes squashfs-root/usr/lib/
cd squashfs-root/usr/lib/
./Ripes
```

**Comment by chuanEgg** [comment]
That worked! Thank you very much. However, I'm still very curious on the subject, perhaps I will spend some time figuring it out.
