### ISSUE TITLE
Missing compiler_explorer.md

### ISSUE THREAD

**Issue by gits00** [mortbopet/Ripes#213]
I was looking at the Cache simulation page at https://github.com/mortbopet/Ripes/blob/master/docs/cache_sim.md  

One of the referred files seems to be missing -  https://github.com/mortbopet/Ripes/docs/compiler_explorer.md
Thanks.

**Comment by mortbopet** [comment]
Thank you for noticing that - fixed in 1a03ff2a723018988582b2427b7f2068250bf5ef.
