### ISSUE TITLE
How do i switch to a single red bar, while debugging?

### ISSUE THREAD

**Issue by xdelu02** [mortbopet/Ripes#220]
![ripes](https://user-images.githubusercontent.com/47484046/186147622-c37acf2d-d5d9-4b06-85e8-416b1a6ef586.png)

At the moment i have this 5 red bar, can i switch to a single one?

**Comment by mortbopet** [comment]
Those bars denote which instruction is in which stage at any given time. A single bar implies a single stage, so you should select the single stage processor model for this.

**Comment by xdelu02** [comment]
Thank you!!
