### ISSUE TITLE
Code not starting and not showing disassambled

### ISSUE THREAD

**Issue by xdelu02** [mortbopet/Ripes#222]
Just opened ripes and this happens. Is like there is no code on the left side.  Tried restarting but is it still like this.

![error](https://user-images.githubusercontent.com/47484046/187997234-a47f16c3-89ab-4568-9548-1036a0e3da51.png)
![eerr](https://user-images.githubusercontent.com/47484046/187997711-af980627-4895-417b-bcc0-b9db4a74f735.png)

**Comment by mortbopet** [comment]
Usually this means that there's an error lurking somewhere in your source program.

**Comment by xdelu02** [comment]
True, thank you
