### ISSUE TITLE
Not showing Pipeline table 

### ISSUE THREAD

**Issue by shakthivels300** [mortbopet/Ripes#225]
![IMG-20220906-WA0011](https://user-images.githubusercontent.com/77143655/188595407-16c9d9e8-cd75-4e5f-af22-e2bd6022222e.jpg)
Thanks

**Comment by mortbopet** [comment]
Does this still occur if your download the newest version (2.2.5)?

**Comment by OBLIVIKRAM** [comment]
Yes it does

**Comment by shakthivels300** [comment]
Yes sir we have downloaded it just last week

**Comment by mortbopet** [comment]
Just to confirm, if you (in Ripes) go to `Help->Version` it says 2.2.5? Which OS are you running?

I am asking, since i am unable to reproduce the error on Windows, using 2.2.5 - for me, the pipeline diagram is generated correctly.

**Comment by shakthivels300** [comment]
We uninstalled and installed fresh download it again it worked properly we were using lubuntu . May be some thing was gone wrong during previous download.
Thank you for your support

**Comment by jnoche** [comment]
FYI: This happened to one of my students who was using v2.2.4. When he replaced it with v2.2.5, the problem was fixed.
