### ISSUE TITLE
The term "block" should really be "word" in cache simulation

### ISSUE THREAD

**Issue by pjlobo** [mortbopet/Ripes#240]
Many textbooks, including Patterson-Hennessy and Hennessy-Patterson, use the names "cache line" and "cache block" as synonymous, referring to either (depending on the context) the data transfer unit to and from main memory or a specific chunk of cache memory where such unit may be stored.

Ripes, however, calls "block" to either (also depending on the context) each of the word indices in a cache line or a specific word in a cache line. I find it very confusing for a newbie who sees the same term with different meanings in the textbooks and in the simulator. As an example, after reading a textbook he or she would expect the labels "2^N Lines" and "2^N Blocks" in the configuration section to be synonymous, while the latter refers to the cache line width, i.e. how many words a cache line contains.

So I'm proposing to substitute "Word" for "Block" in the cache simulation UI and associated docs. I have prepared a pull request which I hope to be able to link to this issue (please bear with me). I have **not** changed the term in the code (variable names and such), as I feel that would be a significant change with an impact in code maintainability and no practical consequences for the final user. I have tested it only on Linux, but there should not be any problem in other platforms as only docs and a few strings are changed.

Finally, let me thank you for coding Ripes and releasing it as open source. I am using it for a course which includes some computer architecture concepts and it's really useful for the students.

**Comment by mortbopet** [comment]
Your argument makes perfect sense. A lot of the documentation (both in and outside the app) was written in a rush just to have _something_. If you find other things that can be clarified or need improvement, feel free to submit more PRs!
