### ISSUE TITLE
Wrong upper range value in memory map

### ISSUE THREAD

**Issue by jnoche** [mortbopet/Ripes#249]
The program below is 24 bytes long and is stored in memory locations 0x00000000 to 0x00000017.
<img width="607" alt="hellotext" src="https://user-images.githubusercontent.com/63948655/203702467-5cc5c1fa-2c4e-457f-97d2-9f0b348de0f5.png">
But the memory map shows that the program is stored in memory locations 0x00000000 to 0x00000018 (an off-by-one error).

**Comment by mortbopet** [comment]
Thanks! fixed in [ab8fca4](https://github.com/mortbopet/Ripes/commit/ab8fca453408aeea6bb40697a560d36d3a44d90b).
