### ISSUE TITLE
Crashes when changing layout 

### ISSUE THREAD

**Issue by atassi122** [mortbopet/Ripes#255]
Hi, 
The Program crashes after changing the layout from "standard" to "extended" on windows 11 22H2. 
And of course after that it woud not open until you go to registry editor and clear the settings,even rebooting won't help.

**Comment by hypermenosh** [comment]
Same problem on windows 10 for Ripes v2.2.5

**Comment by slinkish** [comment]
I believe this is also happening on the linux v2.2.5 AppImage binary, terminal output after switching to "extended" and similarly faulty setting is properly saved to `~./config/Ripes/Ripes.conf` so that the binary crashes immediately with the setting. 
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
zsh: IOT instruction (core dumped)  ./Ripes-v2.2.5-linux-x86_64.AppImage
```

**Comment by mortbopet** [comment]
Fairly sure this is due to what was fixed by https://github.com/mortbopet/Ripes/commit/5176a80b8fb3e1caf8e80b144a8f0cdb755336f9. I'll release a new version of Ripes soon seeing as multiple people are encountering this.

**Comment by mortbopet** [comment]
Went ahead and drafted up a new release https://github.com/mortbopet/Ripes/releases/tag/v2.2.6. Will close this issue for now since I'm fairly confident that the issue was resolved there. However, if not, feel free to re-open the issue.
