### ISSUE TITLE
Does not run on Ubuntu 14.04

### ISSUE THREAD

**Issue by probonopd** [mortbopet/Ripes#26]
Does not run on Ubuntu 14.04:

```
AppRun: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /run/firejail/appimage/.appimage-10255/AppRun)
```

Please see https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#creating-appimages-that-are-compatible-with-many-systems.

Reference:
https://github.com/AppImage/appimage.github.io/pull/831

**Comment by surprized** [comment]
Ubuntu 14.04 was already close to EOL by then, I suggest closing this.
