### ISSUE TITLE
Hexadecimel constants are treated as unsigned numbers 

### ISSUE THREAD

**Issue by RatkoFri** [mortbopet/Ripes#268]
Hexadecimal constants are treated as unsigned numbers, which prevents users to run this instruction: 

addi x2, x0, 0xAFF 

Although the hexadecimal value is 12bit, the Ripes will interpret it as an unsigned number which is out of range for a 12bit signed number (2nd complement). The Ripes will prevent this code for executing

**Comment by mortbopet** [comment]
That was indeed a bug! Should have been fixed in [605cb01](https://github.com/mortbopet/Ripes/commit/605cb01c7effadffa422241a86cc301c56a21666).

**Comment by RatkoFri** [comment]
Thank you very much !
