### ISSUE TITLE
Reset does not clear memory mapped I/O

### ISSUE THREAD

**Issue by honi** [mortbopet/Ripes#269]
For example, add a LED Matrix and turn on some leds. Then click the reset button. The LED Matrix still displays the turned on leds instead of all black.

I assume it's because the memory region mapped to the LED Matrix is not cleared?

**Comment by mortbopet** [comment]
Should hopefully have been fixed in [b67d690](https://github.com/mortbopet/Ripes/commit/b67d690f2c39a0c272945a3791c8fd72ff8f3379).
