### ISSUE TITLE
Issue if infinite loop starts accidently

### ISSUE THREAD

**Issue by anasshamoon12002** [mortbopet/Ripes#30]
**Infinite Loop when run in the application**

Whenever, there is an instruction that starts the loop to run infinitely many times, the program does not provide any function to stop it. 
We have to close the application using task manager.
I hope, that it gets fixed very soon.

**Comment by mortbopet** [comment]
Do you have a code example?

Executing the following by pressing "run":
`
a:
j a
`
Will present a box for aborting the simulation.

**Comment by anasshamoon12002** [comment]
Yup, for your code, it does show the "abort" dialogue box.

Try the following code.

a:
li a1, 10
li a0, 1
ecall
j a

**Comment by anasshamoon12002** [comment]
@mortbopet 

Yup, for the above code, it does show the dialogue box.

Try the following code.

a:
li a1, 10
li a0, 1
ecall
j a

**Comment by mortbopet** [comment]
Fix is available in the latest continuous release - let me know if it fixes your issies!

**Comment by anasshamoon12002** [comment]
@mortbopet 

Yup, the latest release fixed the issue, and it's now working very well.

Thanks for fixing it.

**Comment by anasshamoon12002** [comment]
@mortbopet 

I wanted to address another issue, that can or can not be addressed as an issue.

There is no option in 'File' to create an assembly program. I have to load the pre-existing examples to write the new code.

**Comment by mortbopet** [comment]
Issues may also be used for feature requests - if you create an issue for the request, i'll add the "Enhancement" label to it.

**Comment by anasshamoon12002** [comment]
@mortbopet 

Ok, I'm filing another issue on the above said missing feature.
