### ISSUE TITLE
There is no option to create a new file in 'File' menu

### ISSUE THREAD

**Issue by anasshamoon12002** [mortbopet/Ripes#32]
Hello there.

I wanted to request for a feature, that is missing in the application.

### There is no option to create a new file in the 'File' menu.

![pic 1](https://user-images.githubusercontent.com/33217423/55285548-b605fb80-53a7-11e9-953e-0a5ce9550ab7.PNG)

In order to write a new code, one has to open the pre-existing examples and edit it.

I hope, the next release adds this feature.

**Comment by mortbopet** [comment]
Let me know what you think :+1:

**Comment by anasshamoon12002** [comment]
@mortbopet 

Great work bro. Seems nice.
