### ISSUE TITLE
Ripes crashes when hovering over the cache statistics chart

### ISSUE THREAD

**Issue by margheritarufi** [mortbopet/Ripes#322]
I have noticed that if the cache is empty (i.e. the simulation hasn't reached a load/store instruction) and the user hovers over the statistics chart in the cache tab (bottom left), Ripes crashes. The error is something like: the pointer to "this" is a null pointer. So there is probably a pointer related to the Qt6 Charts library that must be set at the very beginning of the simulation, before any (potential) access to the cache.

In the latest release of Ripes (that uses Qt5) this problem doesn't occur.

**Comment by raccog** [comment]
@margheritarufi Thank you for reporting this bug!

I submitted a pull request here that fixes it: #324.
