### ISSUE TITLE
Assembly source code execution highlight only works with default .text start address

### ISSUE THREAD

**Issue by Aurelio-AVB** [mortbopet/Ripes#355]
Hi,

I was doing some testing and noticed that the source code execution highlight only appears when the start address for the .text section is the default (0x00000000).

![image](https://github.com/mortbopet/Ripes/assets/61214409/04525fb5-d51c-4350-a362-53b958e851bb)

If I change the .text start address source code highlight does not appear 
![image](https://github.com/mortbopet/Ripes/assets/61214409/81e9a41e-ce3e-4b7c-bc98-1295a40adbe8)

I am using ripes 2.2.6-41-gb71f0dd on Win11.

Thanks for any input and regards,
Aurelio Villalpando

**Comment by mortbopet** [comment]
Thank you for reporting this; i'm sure this'll be an easy thing to fix - suspecting that the PC is used to index the text blocks in the code editor, but we're never doing the math to also account for a non-zero starting address of the code. Will look into it asap!

**Comment by mortbopet** [comment]
@Aurelio-AVB should be fixed now; please let me know if it works for you, and if not, feel free to reopen.
