### ISSUE TITLE
unreachable code for REMU in rv_alu.h

### ISSUE THREAD

**Issue by ilyakurdyukov** [mortbopet/Ripes#361]
https://github.com/mortbopet/Ripes/blob/878087332afa3558dc8ca657f80a16ecdcf82818/src/processors/RISC-V/rv_alu.h#L105

This is literally unreachable code that was copied from DIV to REMU. GCC seems to be blind to notice this, but the EDG frontend sees this.

**Comment by mortbopet** [comment]
Thank you for noticing; fixed in [0af6a3f](https://github.com/mortbopet/Ripes/commit/0af6a3fd9fc0c16e47fb814bc13b7cad56d4cdd7).
