### ISSUE TITLE
LI pseudo-instruction error?

### ISSUE THREAD

**Issue by RiadhENIT** [mortbopet/Ripes#41]
Hello,
The following assembly pseudo-instruction
li			a0,0x1000
is translated into
lui x10 2
instead of
lui x10 1

**Comment by mortbopet** [comment]
This should have been fixed previously.
Have you tried with one of the [continuous builds](https://github.com/mortbopet/Ripes/releases)?

**Comment by RiadhENIT** [comment]
OK, thank you for your response and sorry for the disturbance.
I was using an older version...
I confirm that it has been fixed in the latest build.
Good luck.
