### ISSUE TITLE
How to compile from tar.gz ?

### ISSUE THREAD

**Issue by emelcher** [mortbopet/Ripes#43]
Hi,

the  AppImage does not work in CentOS7.
How do I compile the source code?
There semms to be no configure.

Best Regards,
Elmar

**Comment by bjorn3** [comment]
https://github.com/mortbopet/Ripes/blob/master/README.md#building

qmake && make

**Comment by bjorn3** [comment]
https://github.com/mortbopet/Ripes/blob/master/README.md#building

qmake && make

**Comment by emelcher** [comment]
Thanks, worked for CentOS 7, but a g++ version >5.2 must be installed
```
sudo yum install qt5-qtbase-devel qt5-qtsvg-devel
export PATH=<path_to_g++_5.3.0>/bin:$PATH
tar xf ~/Downloads/Ripes*.tar.gz 
cd Ripes*
qmake-qt5
sed -i s/gnu++1y/c++14/g Makefile
make
```
