### ISSUE TITLE
Image in README not found

### ISSUE THREAD

**Issue by bjorn3** [mortbopet/Ripes#45]
![image](https://user-images.githubusercontent.com/17426603/71745357-29bec280-2e6a-11ea-85d7-3bdbe76980fa.png)

**Comment by mortbopet** [comment]
Hello @bjorn3,
Due to some maintenance today, various paths such as the image paths shown in the README.md were changed. These changes have been reflected in 980d2cf588506a57433313f74a06d97240ecfc39.

**Comment by bjorn3** [comment]
Thanks
