### ISSUE TITLE
mul is not being assembled

### ISSUE THREAD

**Issue by rma6** [mortbopet/Ripes#5]
I'm trying to use the instruction mul (mul x10, x11, x12) but it won't assemble.

**Comment by mortbopet** [comment]
thank you for finding the issue - seems like support for mul, mulhu, div, rem etc. operations has been implemented in the simulator, but not in the assembler. I'll take a look at it.

**Comment by mortbopet** [comment]
There was no formal support for the RV32M extension - this has been added in commit 6488abb24f5cda94a1a662ebd8b63d4ce272ab5b.
