### ISSUE TITLE
Can't see full entries in Address column

### ISSUE THREAD

**Issue by jnoche** [mortbopet/Ripes#51]
I am currently using Ripes version v2.0.1-1-g9578aef on an x64-based PC running Microsoft Windows 10 Home Single Language version 10.0.18363 Build 18363.  I am using it to teach a Computer Architecture course and I am very grateful that you have made the software freely available.

<img width="444" alt="Address" src="https://user-images.githubusercontent.com/63948655/79682685-c90b9800-8256-11ea-8138-b43934b12de5.png">

I cannot see the full entries for the Address column in the Memory tab.  I've tried changing the display type and right-clicking and double-left-clicking on the cells.  I cannot change the width of the column using my mouse.

Is there a way to see the full entries for the Address column in the Memory tab?

Thank you very much for your time.

**Comment by jnoche** [comment]
Even though I can't change the width of the Address column, I am able to change the width of the other columns.  If I hover my mouse pointer over the right side of the Word column and reduce its width, the width of the Address column increases.  It seems that the sum of the widths of the Address and Word columns are set to some constant.

<img width="441" alt="Word" src="https://user-images.githubusercontent.com/63948655/79685295-4db3e180-826a-11ea-92f5-9020b549a68d.png">

**Comment by jnoche** [comment]
It seems that the sum of the widths of _all_ the columns are set to some constant.  I was finally able to display the full entries for all the columns by making the widths of all the other columns smaller.

<img width="441" alt="ok" src="https://user-images.githubusercontent.com/63948655/79685363-e9455200-826a-11ea-8311-39c3d38de685.png">

**Comment by mortbopet** [comment]
Unfortunately, the default sizing of that window is a fixed size in the current 2.0 release.
This is going to be addresses in release 2.1 which should be out within the next couple of weeks.
I see that you've found somewhat of a workaround; if you find that the workaround is insufficient, i can push a hot-fix which can be available as a continuous release. Please let me know!

**Comment by jnoche** [comment]
Thanks for your quick reply.  My workaround is enough for now; there is no need for a hot-fix.  Thanks again.
