### ISSUE TITLE
Display decimal immediate in hexadecimal format for some instructions in "Executable Code"

### ISSUE THREAD

**Issue by TorosFanny** [mortbopet/Ripes#52]
Please simply try this code
```
.text
  auipc a0 10  // auipc a0 0x10
  lui t0 10  // lui t0 0x10
  auipc a0 0x10  // auipc a0 0x16
  lui t0 0x10  // lui t0 0x32
```
The comments is what displayed in the 'Executable Code' window.

The issue is not true for some other instructions such as addi.

**Comment by mortbopet** [comment]
Hello @TorosFanny 
Thank you for finding the issue; the issue has been fixed in the referenced commit.

**Comment by TorosFanny** [comment]
I'm not sure if this issue exists for other instructions. Please take care
