### ISSUE TITLE
Build Instructions

### ISSUE THREAD

**Issue by ClemensFMN** [mortbopet/Ripes#54]
I tried to build on Linux and it seems the git submodules need to be pulled in.

`git clone https://github.com/mortbopet/Ripes.git`
`git submodule init`
`git submodule update`
`cd external/VSRTL`
`git submodule init`
`git submodule update`

`cmake .`
`make`

**Comment by mortbopet** [comment]
This may alternatively be performed through the clone command; 
`git clone --recursive https://github.com/mortbopet/Ripes.git`

I've added a comment to your pull request.
