### ISSUE TITLE
Please provide a new release

### ISSUE THREAD

**Issue by rma6** [mortbopet/Ripes#6]
I tried to build the application and deply it but I'm getting error 0xc000007b.
Could you provide a new release with recent comits?

**Comment by mortbopet** [comment]
A new release will be upcoming, but i'd like to gather a few more bugfixes, since the latest release was [5 days ago](https://github.com/mortbopet/Ripes/releases/tag/1.0.1)

**Comment by mortbopet** [comment]
@rma6 
A release with the RV32M extension has now been added:
https://github.com/mortbopet/Ripes/releases/tag/1.0.2
