### ISSUE TITLE
Console printing

### ISSUE THREAD

**Issue by gbest914** [mortbopet/Ripes#60]
I have encountered a problem with console printing. I don't really know how to reproduce the error because it happened from an iteration to another, without me changing any of the code. The message printing is always A�#

![Screenshot (1)](https://user-images.githubusercontent.com/48727416/90972828-92070500-e51c-11ea-96c4-62a9f83e06de.png)
![Screenshot (2)](https://user-images.githubusercontent.com/48727416/90972830-929f9b80-e51c-11ea-9db7-304d84d09112.png)

**Comment by gbest914** [comment]
This is the full code of my program. Now i will try to update the version of ripes


.data
myplaintext: .asciz "Prova"
mycypher: .asciz "A"
sostK: .word 1
blocKey: .asciz "test"
newline:    .string      "\n"
jumpTable: .word 4
cypherText: .word 127

.text

main:
	addi sp,sp,-60			#Salvo valori considerando il main come potenziale "chiamato"
	sw s0,0(sp)
	sw s1,4(sp)
	sw s2,8(sp)
	sw s3,12(sp)
	sw s4,16(sp)
	sw s5,20(sp)
	sw s6,24(sp)
	sw s7,28(sp)
	sw s8,32(sp)
	sw s9,36(sp)
	sw s10,40(sp)
	sw s11,44(sp)
	sw sp,48(sp)
	sw gp,52(sp)
	sw ra,56(sp)

	#Riempio la jump table in base ai case/algoritmi da applicare
	la s5,jumpTable
	la t1,A
	sw t1,0(s5)						
	la t1,B
	sw t1,4(s5)
	la t1,C
	sw t1,8(s5)
	la t1,D
	sw t1,12(s5)

	la t0, myplaintext
	li t1, 0
	li t2, 0
ContaCifrePlainText:
	add t2, t1, t0
	lb t3, 0(t2)
	beq t3, zero, FinePlainText
	addi t1, t1, 1
	j ContaCifrePlainText
FinePlainText:	
	li s1, 0
	add s1, s1, t1
	
	la t0, mycypher
	li t1, 0
	li t2, 0
ContaCifreCypher:
	add t2, t1, t0
	lb t3, 0(t2)
	beq t3, zero, FineCypher
	addi t1, t1, 1
	j ContaCifreCypher
FineCypher:	
	li s2, 0
	add s2, s2, t1
	
SetSostK:
	li t3, 0
	la t6, sostK
	addi t3, t3, 5
	sw t3, 0(t6)
	
#CIFRATURA
	add s0,sp,zero
	#Uso fp per scorrere lo stack senza estrarre elementi che dopo dovranno essere riutilizzati.
	#Si inizializza in questo punto del codice affinchè resti il medesimo nonostante i successivi push
	la t0, myplaintext         				#Uso registro ausiliaro per salvare la posizione iniziale del buffer
	add t1,s1,zero							#Uso registro ausiliario per salvare la lunghezza del messaggio
	add s0, sp, zero
CicloReadFromBuffer:
	beq zero, t1, Continua1   				#Condizione uscita dal ciclo
	addi sp, sp,-4							#Push nella stack->NECESSARIO DEALLOCARE LO SPAZIO AL TERMINE DEL PROGRAMMA
	lb t2, 0(t0)
	sw t2, 0(sp)							#Scorro di una posizione nella stack tramite registro ausiliaro con l'inderizzo del buffer
	addi t0, t0, 1							#Aggiorno la posizione in lettura: Scorro "messaggio"
	addi t1, t1, -1							#Decremento l'indice
	j CicloReadFromBuffer
Continua1:
	la t0, myplaintext
	add t1,s1,zero
	la t3, cypherText
CopiaMessaggioInCypherText:
	beq zero, t1, Continua   				#Condizione uscita dal ciclo
	lb t2, 0(t0)
	sw t2, 0(t3)							#Scorro di una posizione nella stack tramite registro ausiliaro con l'inderizzo del buffer
	addi t3, t3, 4
	addi t0, t0, 1							#Aggiorno la posizione in lettura: Scorro "messaggio"
	addi t1, t1, -1							#Decremento l'indice
	j CopiaMessaggioInCypherText
Continua:
	addi s0, s0, -4
	add a0,zero,zero						#a0=0 CIFRATURA
	li a5, 0
	add a5, a5, s1							#salvo in a2 la lunghezza del messaggio per passarla alle procedure relative agli algoritmi di cifratura/decifratura
	li a3, 0
	add a3, a3, s0							#salvo in a3 il valore di fp per passarlo alle procedure relative agli algoritmi di cifratura/decifratura e per potervi operare senza influenzare fp direttamente
	jal Inizializzo
	li s1, 0
	add s1, s1, a0							#in s0 vi è la lunghezza del messaggio totalmente cifrato
	li sp, 0
	add sp, sp, a1							#in sp c'è ora l'effettivo fondo della stack
#Scrittura su messaggioCifrato.txt

#Decifratura:                   			#CONVENZIONI:opero su a0 e avvio una procedura con a0
	addi a0,zero,1							#a0=1 DECIFRATURA
	li a5, 0
	add a5, a5, s1							#salvo in a2 la lunghezza del messaggio per passarla alle procedure relative agli algoritmi di cifratura/decifratura
	li a3, 0
	add a3, a3, s0							#salvo in a3 il valore di fp per passarlo alle procedure relative agli algoritmi di cifratura/decifratura e per potervi operare senza influenzare fp direttamente
	jal Inizializzo
	li s1, 0
	add s1, s1, a0							#in s0 vi è la lunghezza del messaggio totalmente cifrato
	li sp, 0
	add sp, sp, a1							#in sp c'è ora l'effettivo fondo della stack
#Scrittura su messaggioDecifrato.txt
	
#Ripristino registri salvati all'inizio del main
	lw ra,40(sp)
	lw gp,36(sp)
	lw sp,32(sp)
	lw s7,28(sp)
	lw s6,24(sp)
	lw s5,20(sp)
	lw s4,16(sp)
	lw s3,12(sp)
	lw s2,8(sp)
	lw s1,4(sp)
	lw s0,0(sp)
	addi sp,sp,44
#Termina il programma e ritorna al chiamante
	jr ra
#Apertura File

#Scrittura su file

#Chiusura File

# Errore

Stampa:
	addi sp,sp,-4
	sw t0,0(sp)
	la a6, myplaintext
	add t0, zero, a5
loop:	
	beq zero, t0, ContinuaStampa
	li a7, 11   									# Argument '4' for ecall instructs ecall to print to console
    ecall
	addi a6, a6, 4
	addi t0, t0, -1
	j loop
ContinuaStampa:
    la a6, newline
    li a7, 4
    ecall
	
	lw t0,0(sp)
	addi sp,sp,4
	jr ra

#FOR e SWITCH
Inizializzo:
	#Salvo registri callee-saved
	jal Stampa
	addi sp,sp,-4
	sw s3,0(sp)
	addi sp,sp,-4
	sw s5,0(sp)
	addi t0, zero, 1
	beq a0, t0, initDecifratura		#se a0 = t0 (ossia a 1) stiamo decifrando, altrimenti si ha cifratura
	add t0, zero, zero 				#indice ciclo dello switch uguale a 0 per la cifratura
	add t2, s2, zero					#limite superiore per il ciclo dello switch
Loop_1:									#questa procedura non altera registri non temporanei
	beq t2, t0, Loop_1_Exit     		#se la chiave è finita esci
	li t3, 0
	add t3, t3, t0
	blt t3, zero, PerMenoUno
CalcoloOffset:
	la s2,mycypher
	add t3, t3, s2				#sommo all'indice l'indirizzo del buffer CHIAVE
	lb t5, 0(t3)						#accedo alla posizione appena calcolata
	sub t3, t3, s2				#sottraggo all'indice l'indirizzo del buffer chiave
	addi t5,t5,-65					#se lettera=A t5=0 ---- lettera=B t5=1.......
	add t5,t5,t5
	add t5,t5,t5              		#moltiplichiamo per 4 t5 per usare lo switch correttamente
	add t1, t5, s5					#(la jump table contiene una label ogni 4 byte)
	lw t6, 0(t1)
	li a1, 0
	add a1, a1, t5					#se a0=1 siamo in a, ecc...

	#Passo fp alla procedura (mediante a3) per modificare il messaggio contenuto nella stack, rendendolo cifrato
	jr t6								#saltiamo alla label corretta (a0 indicherà cifratura o decifratura)
RitornoDaAlgoritmo:
	addi t0, t0, 1 							#i = i+1;
	li a2, 0
	add a2, a2, a0
	li sp,0
	add sp, sp, a1						#Posso modificare sp perchè l'ho salvato sulla stack
	jal CopiaMessaggio
	jal Stampa
	j Loop_1 # goto Loop
Loop_1_Exit:
	li a1, 0
	add a1, a1, sp					#Ritorno il valore di sp da modificare (necessario per modifica)->potrei farlo subito ma violerei le convenzioni del chiamato
	#Ripristino registri callee-saved
	lw s5,0(sp)
	addi sp,sp,4
	lw s3,0(sp)
	addi sp,sp,4
	li a0, 0
	add a0, a0, a2							#Ritorno la lunghezza del messaggio (necessario per modifica)
	jr ra										#torno al chiamante
PerMenoUno:
	mul t3,t3,t6
	j CalcoloOffset
initDecifratura:						#passare s1 in un registro a
	addi t0, s2, -1 				#in t0 mettiamo la lunghezza della chiave - 1: Il valore precedente alla chiamata non è più necessario e non è stato salvato
	addi t6, zero, -1				#t6 contiene ora -1
	mul t0,t0,t6						#moltiplichiamo il contenuto di t0 per -1: Ora possiamo usare t0 per inizializzare l'indice del ciclo usato per lo switch
	addi t2, zero, 1				#limite superiore per il ciclo dello switch
	j Loop_1

A:										#Cifrario a sostituzione
	addi sp,sp,-8					#Salvo valori che servono per il ciclo di Inizializzo
	sw t0,0(sp)
	sw t2,4(sp)
	la t6, sostK
	lw t5, 0(t6)
	li t2, 0
	addi t2, t2, 1
	beq a0,t2,ADecifratura				#se sto decifrando
	li t2, 0
CicloA:	
	bge	t2, a2, EsciA					#Condizione di uscita
	lw t4, 0(a3)
	slti t0, t4, 91
	slti t1, t4, 65
	bne t0, t1, ToUpperCase			#Condizione per cui il carattere in esame è A-Z
	slti t0, t4, 123
	slti t1, t4, 97
	bne t0, t1, ToLowerCase			#Condizione per cui il carattere in esame è a-z
	addi t2, t2, 1
	addi a3, a3, -4					#aumenta il contatore e prosegui lasciando inalterato il valore
	j CicloA
ToUpperCase:
	add t4, t4, t5
	slti t1, t4, 91
	beq t1, zero, OverflowUpper
	slti t3, t4, 65
	bne t3, zero, UnderflowUpper		#controllo che i caratteri A-Z non divengano altri caratteri non permessi dalla specifica
	sw t4, 0(a3)
	addi a3, a3, -4
	j CicloA
ToLowerCase:	
	add t4, t4, t5
	slti t1, t4, 123
	beq t1, zero, OverflowLower
	slti t3, t4, 97
	bne t3, zero, UnderflowLower		#controllo che i caratteri a-z non divengano altri caratteri non permessi dalla specifica
	sw t4, 0(a3)
	addi a3, a3, -4
	j CicloA
OverflowUpper:							#Seguono casi in cui la codifica ascii ha un valore troppo grande o troppo piccolo per essere una lettera
	addi t4, t4, -26
	slti t1, t4, 91
	beq t1, zero, OverflowUpper
	sw t4, 0(a3)
	addi a3, a3, -4
	j CicloA
UnderflowUpper:
	addi t4, t4, 26
	slti t1, t4, 65
	bne t1, zero, UnderflowUpper
	sw t4, 0(a3)
	addi a3, a3, -4
	j CicloA
OverflowLower:
	addi t4, t4, -26
	slti t1, t4, 123
	beq t1, zero, OverflowLower
	sw t4, 0(a3)
	addi a3, a3, -4
	j CicloA
UnderflowLower:
	addi t4, t4, 26
	slti t1, t4, 97
	bne t1, zero, UnderflowLower
	sw t4, 0(a3)
	addi a3, a3, -4
	j CicloA
ADecifratura:
	li t0, 0
	addi t0, t0, -1
	mul t5,t5,t0						#Necessario perchè il ciclo funzioni anche in decifratura senza duplicare codice
	j CicloA
EsciA:									
	lw t2,4(sp)						#Ripristino valori che servono per il ciclo di Inizializzo
	lw t0,0(sp)
	addi sp,sp,8	
	j RitornoDaAlgoritmo

B:
	addi sp,sp,-8					#Salvo valori che servono per il ciclo di Inizializzo
	sw t0,0(sp)
	sw t2,4(sp)
	la t0, blocKey
	li t1, 0
	li t2, 0
ContaCifreBlocKey:
	add t2, t1, t0
	lb t3, 0(t2)
	beq t3, zero, FineConta
	addi t1, t1, 1
	j ContaCifreBlocKey
FineConta:
	li t2, 0
Reinizializza:
	li t3, 0
	li t6, 0
	addi t6, t6, 1
	beq a0,t6,BDecifratura				#se sto decifrando
CicloB:
	bge	t2, a2, EsciB					#Condizione di uscita
	beq t3, t1, Reinizializza
	lb t4, 0(a3)						#considero il carattere in esame
	addi t4, t4, -32					#ci sottraggo 32
	add t6, t3, t0
	sb t5, 0(t6)						#considero il carattere della chiave di blocco in esame
	addi t5, t5, -32					#ci sottraggo 32
	add t4, t4, t5					#a questo punto posso sommare i due valori
	addi t5, zero, 96
	rem t4, t4, t5					#e fare l'operazione di modulo
	addi t4, t4, 32					#sommo 32 al risultato
	sb t4, 0(a3)						#e lo metto in memoria
	addi t3, t3, 1					
	addi a3, a3, -1
	addi t2, t2, 1				
	j CicloB
BDecifratura:
	bge	t2, a2, EsciB					#Condizione di uscita
	beq t3, t1, Reinizializza
	lb t4, 0(a3)
	add t6, t3, t0
	sb t5, 0(t6)
	addi t5, t5, -32
	sub t4, t4, t5
	sb t4, 0(a3)
	addi t3, t3, 1
	addi a3, a3, -1
	addi t2, t2, 1
	j BDecifratura
EsciB:
	lw t2,4(sp)						#Ripristino valori che servono per il ciclo di Inizializzo
	lw t0,0(sp)
	addi sp,sp,8	
	j RitornoDaAlgoritmo

C:
	beq a0,zero,CCifratura				#se a0 è uguale a 0 sto cifrando
CDecifratura:
	addi sp,sp,-40						#salvo sp perchè la procedura lo altererà (SARA' MODIFICATO IN SEGUITO PASSANDO IL SUO VALORE CON v0)
	sw sp,0(sp)
	sw s0,4(sp)
	sw s1,8(sp)
	sw s2,12(sp)
	sw s3,16(sp)
	sw s4,20(sp)
	sw s5,24(sp)
	sw s6,28(sp)
	sw s7,32(sp)
	sw s8,36(sp)
	li t1,0								#inizializzo variabile LUNGHEZZA MESSAGGIO DECIFFRATO
	li t2,0								#inizializzo indice ciclo FOR_1
CicloScorrimentoMessDec:    			#FOR_1
	bge t2,a2,EsciScorriDec 			#condizione di uscita: se indice minore di lunghezza messaggio
	add t3,t2,t2
	add t3,t3,t3						#CALCOLO OFFSET (indice * 4)
	sub t3,a3,t3						#FP - OFFSET
	lw t4,0(t3)							#salvo in t4 la i-esima lettera del messaggio da decrifrare
	addi t2,t2,1						#i++
CicloCercaSpazioOFine:
	add t3,t2,t2
	add t3,t3,t3						#CALCOLO OFFSET (indice * 4)
	sub t3,a3,t3						#FP - OFFSET
	lw t5,0(t3)							#salvo in t5 la nuova i-esima lettera del messaggio da decrifrare (ovvero trattini e numeri che seguono la lettera)
	li s7, 0
	addi s7, s7, 32
	beq t5,s7,EsciCicloCercaSpazio	 	#1° condizione di uscita: se la lettera i-esima ora calcolata è uguale al carattere spazio (ASCII: 32)
	bge t2,a2,EsciCicloCercaSpazio 		#2° condizione di uscita: se indice minore di lunghezza messaggio
	addi t2,t2,1						#i++ (salto trattino)
	li t6, 0
	add t6, t6, sp							#uso stack a partire da sp per contare le cifre dopo il trattino e calcolare il numero che rappresentano
	li s3,0								#uso variabile per contare cifre (s3) inizializzata a 0
	li s1, 0
	add s1, s1, sp							#salvo il valore di sp in s1 per lavorare solo sulle cifre nella stack
CicloContaCifre:
	add t3,t2,t2
	add t3,t3,t3						#CALCOLO OFFSET (indice * 4)
	sub t3,a3,t3						#FP - OFFSET
	lw t5,0(t3)							#salvo in t5 la nuova i-esima lettera del messaggio da decrifrare (ovvero trattini e numeri che seguono la lettera)
	li s8, 0
	addi s8, s8, 45	
	beq t5,s7,EsciControlloContaCifre	#1° condizione di uscita: se la lettera i-esima ora calcolata è uguale al carattere spazio (ASCII: 32)
	beq t5,s8,EsciControlloContaCifre	#2° condizione di uscita: se la lettera i-esima ora calcolata è uguale al carattere trattino (ASCII: 45)
	bge t2,a2,EsciControlloContaCifre 	#3° condizione di uscita: se indice minore di lunghezza messaggio
	addi s1,s1,-4						#Inserisco nella stack la cifra indicata dal registro t7
	sw t5,0(s1)							#Inserisco ora nella stack la cifra sopra citata
	addi s3,s3,1						#Incremento numero cifre
	addi t2,t2,1						#i++
EsciControlloContaCifre:
	li t5,0								#(t5 è ora riutilizzabile) Uso t5 come contatore (k) del ciclo che seguirà
	li s4,0								#Uso s4 per mantenere la posizione che calcoleremo a partire dalle sue cifre
CicloCalcolaPosizione:
	bge t5,s3,EsciCalcoloPosizione
	addi s1,s1,-12						#salvo ra
	sw ra,0(s1)
	sw a0,4(s1)
	sw a1,8(s1)
	li a0,10
	sub a1,s3,t5						#variabileContaCifre - k
	addi a1,a1,-1						#variabileContaCifre - k - 1
	jal PotenzaDi10
	lw ra,0(s1)							#Ripristino registri salvati
	lw a0,4(s1)
	lw a1,8(s1)
	addi sp,sp,12
	add s5,t5,t5
	add s5,s5,s5						#CALCOLO OFFSET (indice k * 4)
	add s5,s1,s1						#posizione k
	lw s6,0(s5)							#salvo in s6 la cifra k-esima
	mul a4,a4,s6						#moltiplico cifra k-esima per 10 alla variabileContaCifre - k - 1
	add s4,s4,a4						#sommo quanto calcolato a t8: al termine del ciclo di calcolo posizione avremo la posizione dove inserire il carattere dato
	j CicloCalcolaPosizione
EsciCalcoloPosizione:
	add s4,s4,s4
	add s4,s4,s4						#CALCOLO OFFSET (posizione calcolata sopra * 4)
	sub s4,sp,s4						#Uso l'offset sopra calcolato per inserire a partire da sp
	sw t4,0(s4)						#inserisco il valore salvato in t4 (usata per appoggio sopra) nell'indirizzo calcolato
	addi t1,t1,1						#incremento il contatore relativo alla lunghezza del messaggio
	j CicloCercaSpazioOFine
EsciCicloCercaSpazio:
	j CicloScorrimentoMessDec
EsciScorriDec:
	add t0,t0,sp
	add s2,t1,t1
	add s2,s2,s2						#lunghezza messaggio per 4
	sub t0,t0,s2						#necessario settare così il fondo della stack per salvare ra
	li a0, 0
	li a1, 0
	li a2, 0
	add a0, a0, sp						#Passaggio parametri
	add a1, a1, t1
	add a2, a2, a3
	addi t0,t0,-4						#Salvo ra
	sw ra,0(t0)
	lw s6,28(sp)
	lw s5,24(sp)
	lw s4,20(sp)
	lw s3,16(sp)
	lw s2,12(sp)						#Ripristino valori salvati ad inizio procedura sulla stack (altrimenti verrebbero sovrascritti
	lw s1,8(sp)						#dalla procedura di ricopiatura)
	lw s0,4(sp)
	lw sp,0(sp)
	addi sp,sp,32
	jal RicopioMessaggio
	lw ra,0(t0)						#Ripristino ra
	addi t0,t0,4
	li a0, 0
	add a0, a0, t1						#Ritorno la nuova lunghezza del messaggio
	j RitornoDaAlgoritmo


PotenzaDi10:
	li a4,1
CicloPotenza:
	beq a1,zero,FinePotenza
	mul a4,a4,a0
	addi a1,a1,-1
FinePotenza:
	jr ra

CCifratura:
	addi sp,sp,-52					#salvo sp perchè la procedura lo altererà (SARA' MODIFICATO IN SEGUITO PASSANDO IL SUO VALORE CON v0)
	sw sp,0(sp)
	sw s0,4(sp)
	sw s1,8(sp)
	sw s2,12(sp)
	sw s3,16(sp)
	sw s4,20(sp)
	sw s5,24(sp)
	sw s6,28(sp)
	sw s7,32(sp)
	sw s8,36(sp)
	sw s9,40(sp)
	sw s10,44(sp)
	sw s11,48(sp)
	li t0, 0
	add t0, t0, sp						#salvo in t0 il valore di sp per poter operare al di sotto del messaggio originale nella stack (sp sarà l'fp della parte di stack in cui verrà posto il messaggio da cifrare/cifrato)
	lw t1,-4(a3)						#salviamo la prima lettera del messaggio in t1: Le lettere ripetute nel messaggio una volta contate saranno sostituite con questa, in quanto il ciclo non dovrà operarvi
	li t2,0							#inizializzazione di t2 indice incrementata per muoversi nel messaggio (serve per sapere quanto è lungo il messaggio al termine della cifratura)
	li t3,0							#inizializzazione indice FOR_1
ScorriMessaggio:						#FOR_1
	bge t3,a2,EsciScorrimento			#Se (indice > lunghezza messaggio) termina FOR_1
	add t4,t3,t3						#---
	add t4,t4,t4						#offset = indice * 4
	sub t5,a3,t4						# (fp - offset) per accedere al carattere (Lavoro sul messaggio,cifrato o meno, non copia)
	lw t6,0(t5)						# carattere corrente = STACK (fp - offset)
	beq t6,t1,ControlloIndice			#IF prima lettera = lettera i-esima nel primo messaggio (non copia)
ProseguoPrimoControllo:
	add s8,t2,t2
	add s8,s8,s8						#indice i moltiplicato per 4 in s8
	sub t0,t0,s8						#in t0 ho la posizione nella stack del carattere in posizione "contatore" (Lavoro sul messaggio,cifrato o meno, copiato nella parte inferiore della stack)
	bne t3,zero,InseriscoSpazio		#Se i!=0 inserisco uno spazio
DopoInsSpazio:
	sw t6,0(t0)						#inserisco la lettera i-esima in posizione "contatore", nella sezione di stack copiata in precedenza
	addi t2,t2,1						#contatore++ (serve solo per sapere quanto è lungo il messaggio al termine della cifratura)
	addi t0,t0,-4 					#devo anche modificare il registro che contiene l'indirizzo del contenuto della posizione "contatore"
	add t4,zero,t3					#uso contatore "j" che salvo in t4, il cui valore può essere ora sovrascritto, per nuovo ciclo
CicloCercaCaratteri:
	bge t4,a2,EsciCercaCaratteri
	add s0,t4,t4
	add s0,s0,s0						#indice j moltiplicato per 4 in s0
	sub s1,a3,s0						#in s1 ho la posizione nella stack del j-esimo carattere (Lavoro sul messaggio,cifrato o meno,copiato nella stack "inferiore")
	sw s2,0(s1)						#salvo in s2 carattere in posizione j-esima
	bne t6,s2,EsciCercaCaratteri 		#se il carattere j-esimo non è uguale all'i-esimo non devo mettere trattini seguiti dalla posizione del carattere
	addi s3,s3,45					  	#codice ASCII del trattino: 45
	sw s3,0(t0)						#inserisco un trattino nel messaggio cifrato
	addi t2,t2,1						#contatore++ (serve solo per sapere quanto è lungo il messaggio al termine della cifratura)
	addi t0,t0,-4 					#devo anche modificare il registro che contiene l'indirizzo del contenuto della posizione "contatore"
	li s4,0							#indice usato per scansionare le cifre
	li s5, 0
	add s5, s5, t4						#salviamo in s5 l'indice del ciclo di ricerca delle lettere uguali per poter ottenere le singole cifre che compongono una posizione per poterle inserire nel messaggio

ContaCifre:
	beq	s5, zero, EsciContaCifre		#se s5 è uguale a 0 significa che abbiamo ottenuto tutte le cifre che componevano la posizione ricercata
	addi s0,s0,10										#s0 è riutilizzabile (usato prima solo per offset): Vi si assegna 10, necessario per l'operazione di modulo				
	rem s11, s5, s0						#salvo in s5 il quoziente e in s11 il resto
	div s5, s5, s0
	sw s11,0(t0)							#push della posizione del carattere nella stack (per ora in ordine inverso)
	addi t2,t2,1						#contatore++ (serve solo per sapere quanto è lungo il messaggio al termine della cifratura)
	addi s4,s4,1						#incremento l'indice usato per la scansione delle cifre
	addi t0,t0,-4 					#devo anche modificare il registro che contiene l'indirizzo del contenuto della posizione "contatore"
	j contaCifre
EsciContaCifre:
	#Inversione delle cifre ottenute: vedi D per funzionamento
	li a0,2									#salvo in a0, che può essere sovrascritto (conteneva 0 in questo caso ad indicare che siamo in cifratura), 2, usato per dividere la lunghezza del messaggio
	div s5,s4,a0  					#calcolo la metà del numero di cifre e la pongo in s5, ora utilizzabile (conteneva un contatore da dividere)
	li s6,0									#indice
	add s9,s4,s4
	add s9,s9,s9						#pongo inizialmente in s9 il valore di s4 moltiplicato per 4
	add s9,t0,t0						#t8 contiene l'indirizzo della prima cifra da invertire
CicloInverti:
	bge s6,s5,EsciInverti					#condizione di uscita
	add a0,s6,s6						#accedo alla posizione i-esima del messaggio, e metto l'indice calcolato in a0 (sovrascrivibile: conteneva 2)
	add a0,a0,a0						#accesso effettuato mediante moltiplicazione dell'indice per 4
	add a0,a0,s9						#mi pongo nella posizione giusta sommando l''indirizzo della cima della stack
	lw a1,0(a0)							#metto in a1 (sovrascrivibile: usato solo per ABC) l'i-esimo carattere
	sub s7,s4,s6						#lunghezzamsg-indice
	addi s7,s7,-1						#lunghezzamsg-indice-1'
	add s7,s7,s7
	add s7,s7,s7						#moltiplico per 4 il valore calcolato per lavorare come sopra in byte
	add s7,s7,s9						#calcolo la posizione da scambiare con quella precedentemente calcolata
	lw a0,0(s7)							#salvo il carattere in posizione lunghezzamsg-indice-1 in a0 (sovrascrivibile: dopo verrà nuovamente sovrascritto senza che il valore che ora sarà inserito sia erroneamente letto)
	sw a1,0(s7)							#metto il carattere in posizione i in posizione lunghezzamsg-indice-1
	sw a0,0(t4)							#metto il carattere salvata dalla posizione lunghezzamsg-indice-1 alla i-esima
	addi s6,s6,1						#incremento l'indice
j CicloInverti
EsciInverti:
	beq t4,t3,IndiciCicliUguali			#Se stiamo controllando la stessa posizione andiamo alla posizione indicata dall'etichetta inserita
	sw t1,0(s1)											#Inserisco la primaLettera nella j-esima posizione della parte inferiore della stack: Così evito controlli inutili su lettere già controllate in precedenza
IndiciCicliUguali:
	addi t4,t4,1										#Incremento indice del FOR_2
	j CicloCercaCaratteri
EsciCercaCaratteri:
	addi t3,t3,1										#Incremento indice del FOR_1
	j ScorriMessaggio
EsciScorrimento:
	li a0, 0
	li a7, 0
	li a2, 0
	add a0, a0, sp
	add a7, a7, t2
	add a2, a2, a3
	addi t0,t0,-4										#Salvo ra
	sw ra,0(t0)

	sw s11,48(sp)
	lw s10,44(sp)
	lw s9,40(sp)
	lw s8,36(sp)
	lw s7,32(sp)										#Ripristino valori salvati ad inizio procedura sulla stack
	lw s6,28(sp)										#altrimenti verrebbero sovrascritti dalla ricopiatura
	lw s5,24(sp)
	lw s4,20(sp)
	lw s3,16(sp)
	lw s2,12(sp)
	lw s1,8(sp)
	lw s0,4(sp)
	lw sp,0(sp)
	addi sp,sp,52
	jal RicopioMessaggio
	lw ra,0(t0)											#Ripristino ra
	addi t0,t0,4
	li a0, 0
	add a0, a0, t2											#Ritorno la nuova lunghezza del messaggio
	j RitornoDaAlgoritmo

ControlloIndice:
	beq t3,zero,ProseguoPrimoControllo	#condizione in OR con quella a riga 332 (se i==0 prosegui ciclo)
	j ScorriMessaggio											#altrimenti salto all'inizio del primo ciclo
InseriscoSpazio:
	addi s10,s10,32					  #codice ASCII dello spazio: 32
	sw s10,0(t0)							#inserisco uno spazio nel messaggio cifrato
	addi t2,t2,1						#contatore++
	addi t0,t0,-4
	j DopoInsSpazio
	
D:										#l'algortimo non necissita di ulteriori tag perchè in codifica/decodifica deve fare sostanzialmente la stessa cosa
	addi sp,sp,-8						#Salvo valori che servono per il ciclo di Inizializzo
	sw t0,0(sp)
	sw t2,4(sp)
	li t2, 0
CicloD:	
	bge	t2, a2, EsciD					#Condizione di uscita
	slti t0, a3, 91
	slti t1, a3, 65
	bne t0, t1, ToUpperCaseD			#Condizione per cui il carattere in esame è A-Z
	slti t0, a3, 123
	slti t1, a3, 97
	bne t0, t1, ToLowerCaseD			#Condizione per cui il carattere in esame è a-z
	slti t0, a3, 58
	slti t1, a3, 48
	bne t0, t1, Numero				#Condizione per cui il carattere in esame è 0-9
	addi t2, t2, 1
	addi a3, a3, -1					#aumenta il contatore e prosegui lasciando inalterato il valore
	j CicloD
ToUpperCaseD:							
	li t0, 0
	li t1, 0
	li t3, 0
	add t0, t0, a3	
	addi t1, t1, 26
	addi t3, t3, 97					
	addi t0, t0, -64					#calcolo la posizione della lettera nell'alfabeto
	sub t1, t1, t0					#trovo il numero da sommare per essere nella posizione giusta
	add t3, t3, t1					#trovo la lettera minuscola che impone la codifica
	sw t3, 0(a3)
	j CicloD
ToLowerCaseD:
	li t0, 0
	li t1, 0
	li t3, 0
	add t0, t0, a3	
	addi t1, t1, 26
	addi t3, t3, 65
	addi t0, t0, -96					#calcolo la posizione della lettera nell'alfabeto
	sub t1, t1, t0					#trovo il numero da sommare per essere nella posizione giusta
	add t3, t3, t1					#trovo la lettera maiuscola che impone la codifica
	sw t3, 0(a3)
	j CicloD
Numero:
	li t0, 0
	li t1, 0
	addi t0, t0, 57
	sub t1, t0, t1 					#sottraggo da 9 il numero nel testo da cifrare/decifrare
	sw t1, 0(a3)
	j CicloD
EsciD:
	lw t2,4(sp)						#Ripristino valori che servono per il ciclo di Inizializzo
	lw t0,0(sp)
	addi sp,sp,8	
	j RitornoDaAlgoritmo
	

RicopioMessaggio:								#ricopio il messaggio cifrato ora calcolato mediante l'esecuzione dell'algoritmo ove prima vi era il messaggio originale o cifrato con un altro algoritmo indicato dal file chiave
												#PARAMETRI NECESSARI: a0= 1° puntatore alla stack(sp)  a1:lunghezza del messaggio  a2:2° puntatore alla stack(fp)
												#DESCRIZIONE PROCEDURA: Ricopiatura delle a1 'celle' puntate da a0 in a2
												#moltiplico contatore per 4 e lo metto in t1 (ora inutilizzato)
												#riporto a0 alla cima dell parte della stack che contiene il messaggio cifrato
	li t3,0									#indice (i) ciclo usato per ricopiatura (t3 utilizzabile)
CicloRicopiatura:
	bge t3,a7,EsciRicopiatura
	addi a2,a2,4								#sommo l'offset calcolato a a3 (posso usarlo in quanto non modifico fp facendolo) per ottenere la posizione in cui copiare l'i-esimo carattere
	addi a0,a0,4								#sommo l'offset calcolato a a0 per ottenere l'i-esimo carattere da copiare
	lw t5,0(a0)								#salvo in t5 il valore da copiare
	sw t5,0(a2)								#inserisco il carattere da copiare nella giusta posizione
	addi t3,t3,1								#incremento indice i
	j CicloRicopiatura
EsciRicopiatura:
	li a1, 0
	add a1, a1, a2								#ritorno l'inizio della stack da assegnare poi a sp
	jr ra
	#COPIA MESSAGGIO CIFRATO NELLA PARTE SUPERIORE DELLA STACK
	
CopiaMessaggio:
	li t3, 0
	la t6, cypherText
	add a3, s0, zero
CicloCopia:
	bge t3,a5,EsciCopia
	addi a3, a3, 4
	lw t5, 0(a3)
	sb t5, 0(t6)
	addi t3, t3, 1
	addi t6, t6, 4
	j CicloCopia
EsciCopia:
	jr ra

**Comment by gbest914** [comment]
But there's no .exe file in the new version

**Comment by gbest914** [comment]
Downloaded the new version and the error still reproduces

**Comment by gbest914** [comment]
I start printing in the point of memory where my message starts but even though it seems that no ascii can be printed

**Comment by gbest914** [comment]
![Screenshot (3)](https://user-images.githubusercontent.com/48727416/91017370-72d8a800-e5ee-11ea-8d28-61204e7d0bb5.png)
![Screenshot (4)](https://user-images.githubusercontent.com/48727416/91017377-7409d500-e5ee-11ea-95cb-1e1f870b0ca1.png)

**Comment by mortbopet** [comment]
Have you verified that is not an error within the provided program? As in, executed the code on another simulator (ie. using RARS or RISC-V Venus). 

Also, have you verified that you are using the correct ecalls and placed the arguments in the appropriate registers? for instance, i noticed that in the following:
```
ContinuaStampa:
la a6, newline
li a7, 4
ecall
```
The address of the `newline` string should be placed in register `a0` and not in `a6`.

**Comment by gbest914** [comment]
Yes, thank you, that was the problem.
