### ISSUE TITLE
Consider enabling the the Discussion feature for this repo

### ISSUE THREAD

**Issue by jontrossbach** [mortbopet/Ripes#64]
Hi,

It might be a good idea to allow the discussion feature on this repo so that people can ask questions about how best to contribute without having to open issues for simple questions.

Just a thought, the feature is in the repo settings.

Jon

**Comment by mortbopet** [comment]
Hi @jontrossbach - thank you for the notice. I've had Gitter enabled for this exact feature but never been fond of asking users to move to a 3rd party site to start a discussion. So this is definitely the better option; thank you for letting me know. The feature is now enabled.

- Morten
