### ISSUE TITLE
Increase font size

### ISSUE THREAD

**Issue by alessandroPalazzolo** [mortbopet/Ripes#67]
Is there a way to increase font size not only relative to console text? I'm using HighSierra 10.13 and code inside the editor is too small.

**Comment by mortbopet** [comment]
Hello @alessandroPalazzolo 
Unfortunately, high-DPI support is a bit lacking in Ripes.
However, on windows/linux, ctrl+scroll in the editor should adjust the font size. I would assume that 'cmd+scroll' on mac should work equivalently. If not, please let me know.

**Comment by alessandroPalazzolo** [comment]
Yes, just tried with "cmd+scroll" , thanks for quick help!
