### ISSUE TITLE
How to generate the layout(.json) file for new processors?

### ISSUE THREAD

**Issue by CriusT** [mortbopet/Ripes#78]
Hi Morten,
I was wondering how I can generate a new layout file for new processors? I modified some of the wires while I use the the same layout file as rv5s. But it turns out to be a mess like the picture below. 
Thanks a lot!
![image](https://user-images.githubusercontent.com/40891932/112782765-620a7c00-9080-11eb-9463-86f6d13a4a44.png)

**Comment by mortbopet** [comment]
This is an area where VSRTL (the underlying simulation and visualization framework) needs some improvement.

You can "unlock" the visualization by right-clicking _outside_ of the processor, and selecting _unlock_. Now you can move around components and intermediate points, remove intermediate points by right-clicking on them, create new intermediate points by right-clicking somewhere on a wire, and merge intermediate points by dragging adjacent points on top of each other.
