### ISSUE TITLE
Installation of version 2.2.0: missing DLL

### ISSUE THREAD

**Issue by MassimilianoMancini** [mortbopet/Ripes#90]
On windows 10 64bit, after installation an error is shown about missing vcruntime140_1.dll.
Fixed by adding the DLL in Ripes directory

<img width="292" alt="error" src="https://user-images.githubusercontent.com/8819943/120592079-86e2ed00-c43d-11eb-8e54-aa4ff6fbe041.png">

**Comment by mortbopet** [comment]
This error is similar to the `msvcp140.dll` error mentioned in [README.md](https://github.com/mortbopet/Ripes/blob/master/README.md) and fixed in the same manner, so I will leave this issue closed due to that.
